const state={selectedRow:0,nextId:1,selectedCardId:null,cards:[],rows:[{horn:false},{horn:false},{horn:false}],weather:"none",leader:"none",gems:[true,true]};
const names=["Corpo a Corpo","À Distância","Cerco"],board=document.getElementById("board"),total=document.getElementById("totalScore");
function weatherHits(r){return(state.weather==="frost"&&r===0)||(state.weather==="fog"&&r===1)||(state.weather==="rain"&&r===2)||(state.weather==="storm"&&(r===0||r===1))}
function rowScore(r){const cs=state.cards.filter(c=>c.row===r),groups={bond:{},bondPlus:{}};
cs.forEach(c=>{if(c.effects.includes("bond"))(groups.bond[c.value]??=[]).push(c);if(c.effects.includes("bondPlus"))(groups.bondPlus[c.value]??=[]).push(c)});
let sum=0;cs.forEach(c=>{let v=c.value;if(!c.effects.includes("hero")){const morale=cs.filter(x=>x.effects.includes("morale")).length;if(!c.effects.includes("morale"))v+=morale;if(weatherHits(r))v=1;if(c.effects.includes("bond"))v*=groups.bond[c.value].length;if(c.effects.includes("bondPlus"))v*=groups.bondPlus[c.value].length}sum+=v});return state.rows[r].horn?sum*2:sum}
function render(){board.innerHTML="";names.forEach((n,r)=>{const cs=state.cards.filter(c=>c.row===r),hit=weatherHits(r),el=document.createElement("section");el.className=`row ${hit?"weather-active weather-"+state.weather:""}`;el.innerHTML=`<div class="row-head"><div class="row-name">${n}</div><div class="row-score">${rowScore(r)}</div><div class="row-controls"><button class="row-control ${state.selectedRow===r?"active":""}" data-row="${r}">+ carta</button><button class="row-control ${state.rows[r].horn?"active":""}" data-horn="${r}">🎺 ×2</button></div></div><div class="cards">${cs.length?cs.map(c=>`<button class="card ${c.effects.includes("bond")?"bond-card":""} ${c.effects.includes("bondPlus")?"bond-plus-card":""} ${c.effects.includes("morale")?"morale-card":""} ${c.effects.includes("hero")?"hero-card":""} ${c.parentId?"bond-child":""}" data-card="${c.id}"><span class="card-value">${c.value}</span><span class="card-icons">${c.effects.includes("bond")?"🔗":""}${c.effects.includes("bondPlus")?"🔒":""}${c.effects.includes("morale")?"❤️":""}${c.effects.includes("hero")?"👑":""}</span></button>`).join(""):`<div class="empty">Nenhuma carta</div>`}</div><div class="row-total">${cs.length} carta${cs.length===1?"":"s"}</div>`;board.appendChild(el)});
total.textContent=[0,1,2].reduce((s,r)=>s+rowScore(r),0);
document.querySelectorAll("[data-row]").forEach(b=>b.onclick=()=>{state.selectedRow=+b.dataset.row;render()});document.querySelectorAll("[data-horn]").forEach(b=>b.onclick=()=>{const r=+b.dataset.horn;state.rows[r].horn=!state.rows[r].horn;render()});document.querySelectorAll("[data-card]").forEach(b=>b.onclick=()=>openCard(+b.dataset.card))}
document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{state.cards.push({id:state.nextId++,row:state.selectedRow,value:+b.dataset.add,effects:[]});render()});
document.querySelectorAll(".gem").forEach(b=>b.onclick=()=>{const i=+b.dataset.gem;state.gems[i]=!state.gems[i];b.classList.toggle("active",state.gems[i])});
function openCard(id){state.selectedCardId=id;const c=state.cards.find(x=>x.id===id);document.getElementById("modalNumber").textContent=c.value;document.querySelectorAll(".effect-btn").forEach(b=>b.classList.toggle("active",c.effects.includes(b.dataset.effect)));document.getElementById("cardModal").classList.remove("hidden")}
document.querySelectorAll(".effect-btn").forEach(b=>b.onclick=()=>{const c=state.cards.find(x=>x.id===state.selectedCardId),e=b.dataset.effect;if(e==="bondPlus"&&!c.effects.includes("bondPlus")){state.cards.push({id:state.nextId++,row:c.row,value:c.value,effects:["bondPlus"],parentId:c.id});close();render();return}const has=c.effects.includes(e);if(has)c.effects=c.effects.filter(x=>x!==e);else{if(e==="hero")c.effects=c.effects.filter(x=>!["bond","bondPlus","morale"].includes(x));if(e==="bond")c.effects=c.effects.filter(x=>x!=="bondPlus");if(e==="bondPlus")c.effects=c.effects.filter(x=>x!=="bond");c.effects.push(e)}render();openCard(c.id)});
document.getElementById("deleteCard").onclick=()=>{const id=state.selectedCardId;state.cards=state.cards.filter(c=>c.id!==id&&c.parentId!==id);close();render()};
document.getElementById("weatherBtn").onclick=()=>document.getElementById("weatherModal").classList.remove("hidden");document.getElementById("leaderBtn").onclick=()=>document.getElementById("leaderModal").classList.remove("hidden");
document.querySelectorAll("[data-weather]").forEach(b=>b.onclick=()=>{state.weather=b.dataset.weather;close();render()});document.querySelectorAll("[data-leader]").forEach(b=>b.onclick=()=>{state.leader=b.dataset.leader;close();render()});
function close(){document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden"))}document.querySelectorAll(".close").forEach(b=>b.onclick=close);
document.getElementById("resetBtn").onclick=()=>{if(!confirm("Reiniciar a partida?"))return;state.selectedRow=0;state.nextId=1;state.selectedCardId=null;state.cards=[];state.rows=[{horn:false},{horn:false},{horn:false}];state.weather="none";state.leader="none";state.gems=[true,true];document.querySelectorAll(".gem").forEach(g=>g.classList.add("active"));render()};render();